version: 0.9.1-beta
spring.jackson.default-property-inclusion: non_null
spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8
spring.resources.static-locations: file:../static