version: 0.12.01
spring.jackson.default-property-inclusion: non_null
spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8
spring.web.resources.static-locations: file:../static/